# Generated by Django 4.1.2 on 2022-11-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdNumber', models.IntegerField(max_length=30, verbose_name='ID Number')),
                ('FullName', models.CharField(max_length=100, verbose_name='Full Name')),
                ('Specialization', models.CharField(max_length=100, verbose_name='Specialization')),
                ('Gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'ordering': ['id', 'FullName'],
            },
        ),
    ]
